jdbc:
  datasource:
    url: jdbc:oracle:thin:@ren7wei:1521:orcl
    username: basic
    password: 123456
    driverClassName: oracle.jdbc.driver.OracleDriver
    maxActive: 100
    maxIdle: 20
    minIdle: 10
    initialSize: 10
    validationQuery: select 1 from dual
    testOnBorrow: false
    testOnReturn: false
  hibernate:
    dialect: org.hibernate.dialect.OracleDialect
    show_sql: true
    packagesToScan:
      - com.ghit.framework.provider.sysmanager.api.model.po
spring: 
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
  mvc:
    media-types:
      - text/html
      - application/json
init: 
  queue:
    contextName: WebApplicationContext
    async:
      - com.ghit.framework.provider.sysmanager.supports.sysmgr.SharpSysmgr$InitOrganization
      - com.ghit.framework.provider.sysmanager.supports.sysmgr.SecurityPolicy$UserInit
      - com.ghit.framework.provider.sysmanager.supports.wf.HiWorkFlowContext$BpdInit
    sync:
      